name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install

      - name: Install build tools (C++ toolchain)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Configure and build C++ plugin with node-gyp
        run: |
          npx node-gyp configure
          npx node-gyp build

      - name: Run tests
        run: npm test
